server:
  port: 15001

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.105:8848
  rabbitmq:
    password: guest
    username: guest
    host: 192.168.0.103
    port: 5672
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/sparkmall_product?serverTimezone=UTC
    username: root
    password: root-xz
  thymeleaf:
    cache: false # 开发阶段关闭 缓存功能，以全能够实时刷新修改后的页面数据
redisson:
  single:
    node: redis://192.168.0.103:6379
