spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/sparkmall_product?serverTimezone=UTC
    username: root
    password: root-xz





  session:
    store-type: redis
  redis:
    host: 192.168.0.106
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**/*Dao.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

