server:
  port: 10000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    password: guest
    username: guest
    host: 192.168.1.186
    port: 5672
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sparkmall_product?serverTimezone=UTC
    username: root
    password: root-xz
