server:
  port: 14001

spring:
  application:
    name: sparkmall-ware

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/sparkmall-ware?serverTimezone=UTC
    username: root
    password: root-xz

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.105:8848


  redis:
    host: 192.168.0.103
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**/*Mapper.xml
