server:
  port: 14001

spring:
  application:
    name: sparkmall-ware



  redis:
    host: 192.168.0.106
    port: 6379
  cloud:
    alibaba:
      seata:
        tx-service-group: tx-trade # 订单交易事务
  profiles:
    active: dev


mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: deleted