spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/sparkmall_ware?serverTimezone=UTC
    username: root
    password: root-xz
  rabbitmq:
    host: 192.168.0.106
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 设置消息签收类型为手动签收
