server:
  port: 10001


spring:
  application:
    name: sparkmall-mail



  #配置邮箱
  mail:
    protocol: smtp
    host: smtp.163.com
    username: 
    password: EUEUKILFEKNYMOCX
    default-encoding: UTF-8
    port: 25
