# 开发环境数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/sparkmall_message?serverTimezone=Asia/Shanghai
    username: root
    password: root-xz
  rabbitmq:
    host: 192.168.0.103
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated

mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**/*Dao.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
