server:
  port: 19001
spring:
  application:
    name: sparkmall-seckill


  rabbitmq:
    virtual-host: /
    host: 192.168.0.106
  redis:
    host: 192.168.0.106

  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  session:
    store-type: redis