server:
  port: 15001


spring:
  application:
    name: sparkmall-pay

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/sparkmall_pay?serverTimezone=UTC
    username: root
    password: root-xz

  redis:
    host: 192.168.0.103
    port: 6379
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    alibaba:
      seata:
        tx-service-group: tx-trade # 订单交易事务
  profiles:
    active: dev


mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**/*Mapper.xml


# 配置 feign 整合 sentinel



feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
