server:
  port: 12001

spring:
  application:
    name: sparkmall-lottery

  # DataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/sparkmall_lottery?serverTimezone=UTC
    username: root
    password: root-xz

  # Redis
  redis:
    host: 192.168.0.103
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.105:8848
  #  rabbitmq:
  #    addresses: 192.168.0.103:5673,192.168.0.103:5674,192.168.0.103:5675
  #    username: guest
  #    password: guest
  #    listener:
  #      simple:
  #        prefetch: 10
  #        acknowledge-mode: manual
  # rabbitmq 单节点配置
  rabbitmq:
    host: 192.168.0.103
    port: 5673
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 10
        acknowledge-mode: manual #设置为手动签收消息


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Dao.xml



logging:
  level:
    com.tingyu.sparkmall: debug
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: status
#      logic-delete-value: 1
