server:
  port: 9001

spring:
  # DataSource
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.105:3306/sparkmall_member?serverTimezone=UTC
#    username: root
#    password: root-xz

  # Redis
  redis:
    host: 192.168.0.103
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.105:8848



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Dao.xml



logging:
  level:
    com.tingyu.sparkmall: info
