server:
  port: 9001

spring:
  application:
    name: sparkmall-member

  # DataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sparkmall_member?serverTimezone=UTC
    username: root
    password: root-xz

  # Redis
  redis:
    host: 192.168.1.186
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Dao.xml



logging:
  level:
    com.tingyu.sparkmall: debug
