server:
  port: 13001

spring:
  application:
    name: sparkmall-order
  profiles:
    active: dev


  redis:
    host: 192.168.0.103
    port: 6379
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    alibaba:
      seata:
        tx-service-group: tx-trade  # 配置事务组名称



mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**/*Dao.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置 feign 整合 sentinel



feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

