server:
  port: 30001


spring:
  application:
    name: sparkmall-coupon # 优惠券微服务
  profiles:
    active: dev # 加载开发环境配置

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mybatis/mapper/**/*Dao.xml


